name: pgbee
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.5
  google_sign_in: ^6.1.5
  http: ^1.4.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  oauth2: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  # To add assets of Application
  assets:
    - assets/images/PgBee.svg
    - assets/images/logo.png
    - assets/images/recaptcha.png
    - assets/images/background.png

  # To add fonts of Application
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/PgBee.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
